# Outer product 

In this notebook, we demonstrate the outer product between two vectors for real and complex operations.

## Outer (real)

Let $\mathbf{x} \in \mathcal{R}^N$ and  $\mathbf{y} \in \mathcal{R}^M$ vectors given by: 

$$ \mathbf{x} = \begin{bmatrix}
x_{0} \\
x_{1} \\
\vdots \\
x_{N-1}
\end{bmatrix}
$$
and
$$ \mathbf{y} = \begin{bmatrix}
y_{0} \\
y_{1} \\
\vdots \\
y_{M-1}
\end{bmatrix}
$$

The outer product is defined as: 

$$ \mathbf{A} = \mathbf{x} \cdot \mathbf{y}^\top =  \mathbf{x} \otimes \mathbf{y}.$$

From this operation, we obtain a matrix with dimension $N \times M$ equal to: 

$$
\mathbf{A} = \begin{bmatrix}
x_0 y_0 & x_0 y_1 &  \cdots & x_0 y_{M-1}\\
\vdots & \vdots &  \ddots &  \vdots   \\
x_{N-1} y_0 & x_{N-1} y_1 & \cdots &  x_{N-1} y_{M-1}
\end{bmatrix}.
$$


**Pseudocode.1:**
    
    for i = 0:N-1
        for j = 0:M-1
            a[i,j] = x[i]*y[j]

**Pseudocode.2:**
    
    for i = 0:N-1
            a[i,:] = x[i]*y[:]

**Pseudocode.3:**
    
    for j = 0:M-1
        a[:,j] = x[:]*y[j]


In [1]:
import numpy as np
import my_functions

In [2]:
x = np.arange(4,dtype=float)

In [3]:
x

array([0., 1., 2., 3.])

In [4]:
y = np.ones_like(x)*2.

In [5]:
y

array([2., 2., 2., 2.])

In [6]:
A = np.outer(x,y)

In [7]:
A

array([[0., 0., 0., 0.],
       [2., 2., 2., 2.],
       [4., 4., 4., 4.],
       [6., 6., 6., 6.]])

In [8]:
A[:,:]

array([[0., 0., 0., 0.],
       [2., 2., 2., 2.],
       [4., 4., 4., 4.],
       [6., 6., 6., 6.]])

In [9]:
A[:,0]

array([0., 2., 4., 6.])

In [10]:
A[0,:]

array([0., 0., 0., 0.])

In [11]:
A[:2,:2]

array([[0., 0.],
       [2., 2.]])

In [12]:
A.shape

(4, 4)

## Outer (complex)

Let $\mathbf{x} \in \mathcal{C}^N$ e  $\mathbf{y} \in \mathcal{C}^M$ vectors with complex entries. The outer product results: 

$$ \mathbf{A} = \mathbf{A}_R + \mathcal{i}*\mathbf{A}_I $$

in which

$$\mathbf{A}_R = \mathbf{x}_R \otimes \mathbf{y}_R - \mathbf{x}_I \otimes \mathbf{y}_I  $$

e

$$ \mathbf{A}_R = \mathbf{x}_R \otimes \mathbf{y}_I + \mathbf{x}_I \otimes \mathbf{y}_R . $$

**Pseudocode:**

    A_R = outer(Real(x), Real(y)) - outer(Imag(x), Imag(y))
    A_I = outer(Real(x), Imag(y)) + outer(Imag(x), Real(y))

    A = A_R + imag*A_I

## Exercises

* Create the functions below according to `template.py`:
  * `outer_real_simple`
  * `outer_real_row`
  * `outer_real_column`
  * `outer_complex`
* These functions must pass the following tests defined in `test_template.py`:
  * `test_outer_real_input_not_vector`
  * `test_outer_real_compare_numpy_outer`
  * `test_outer_real_known_values`
  * `test_outer_real_transposition`
  * `test_outer_real_distributivity`
  * `test_outer_real_scalar_multiplication`
  * `test_outer_real_ignore_complex`
  * `test_outer_complex_compare_numpy_outer`
  * `test_outer_complex_invalid_function`