# Hadamard product

This notebook shows a hadamard product (also known as entrywise product) between two vector and two matrices with real and complex numbers.

## Hadamard product of two vectors (real)

Let $\mathbf{x}, \mathbf{y} \in \mathcal{R}^N$ vectors with real entries given by: 

$$ \mathbf{x} = \begin{bmatrix}
x_{0} \\
x_{1} \\
\vdots \\
x_{N-1}
\end{bmatrix}
$$
and
$$ \mathbf{y} = \begin{bmatrix}
y_{0} \\
y_{1} \\
\vdots \\
y_{N-1}
\end{bmatrix}
$$

The hadamard product (entrywise product) is defined as: 

$$ \mathbf{z} = \mathbf{x} \circ \mathbf{y}.$$

From this operation, we obtain a vector with dimension $N \times 1$ equal to: 

$$
\mathbf{z} = \begin{bmatrix}
x_0 y_0 \\
\vdots \\
x_{N-1} y_{N-1}
\end{bmatrix}.
$$


**Pseudocode.1:**
    
    for i = 0:N-1
            z[i] = x[i]*y[j]

**Pseudocode.2:**
    
    z[:] = x[:]*y[:]

In [1]:
import numpy as np

In [2]:
x = np.arange(4,dtype=float)

In [3]:
x

array([0., 1., 2., 3.])

In [4]:
y = np.ones_like(x)*2.

In [5]:
y

array([2., 2., 2., 2.])

In [6]:
z = x * y

In [7]:
z

array([0., 2., 4., 6.])

## Hadamard product of two vectors (complex)

Let $\mathbf{x}, \mathbf{y} \in \mathcal{C}^N$ vectors with complex entries. The hadamard product betweeb them results: 

$$ \mathbf{z} = \mathbf{z}_R + \mathcal{i}*\mathbf{z}_I $$

in which

$$\mathbf{z}_R = \mathbf{x}_R \circ \mathbf{y}_R - \mathbf{x}_I \circ \mathbf{y}_I  $$

and

$$ \mathbf{z}_I = \mathbf{x}_R \circ \mathbf{y}_I + \mathbf{x}_I \circ \mathbf{y}_R . $$

**Pseudocode:**

    z_R = hadamard(Real(x), Real(y)) - hadamard(Imag(x), Imag(y))
    z_I = hadamard(Real(x), Imag(y)) + hadamard(Imag(x), Real(y))

    z = z_R + imag*z_I

## Hamard product of two matrices (real)

Let $\mathbf{A}, \mathbf{B} \in \mathcal{R}^{N \times M}$ matrices with real entries given by: 

$$
\mathbf{A} = \begin{bmatrix}
a_{00}    & \cdots & a_{0(M-1)}\\
\vdots    &        &  \vdots   \\
a_{(N-1)0}& \cdots &  a_{(N-1)(M-1)}
\end{bmatrix}.
$$
and
$$
\mathbf{B} = \begin{bmatrix}
b_{00}    & \cdots & b_{0(M-1)}\\
\vdots    &        &  \vdots   \\
b_{(N-1)0}& \cdots &  b_{(N-1)(M-1)}
\end{bmatrix}.
$$

The hadamard product (entrywise product) is defined as: 

$$ \mathbf{C} = \mathbf{A} \circ \mathbf{B}.$$

From this operation, we obtain also a matrix with dimension $N \times M$ equal to: 

$$
\mathbf{C} = \begin{bmatrix}
a_{00}b_{00}        & \cdots & a_{0(M-1)}b_{0(M-1)}\\
\vdots              &        &  \vdots   \\
a_{(N-1)0}b_{(N-1)0}& \cdots &  a_{(N-1)(M-1)}b_{(N-1)(M-1)}
\end{bmatrix}.
$$

**Pseudocode.1 :**

    for i = 0:N-1
        for j = 0:M-1
            C[i,j] = A[i,j]*B[i,j]

**Pseudocode.2 :**

    C[:,:] = A[:,:]*B[:,:]

In [8]:
A = np.arange(6,dtype=float).reshape(3,2)

In [9]:
A

array([[0., 1.],
       [2., 3.],
       [4., 5.]])

In [10]:
A.shape

(3, 2)

In [11]:
B = np.linspace(10,20,num=6,dtype=float).reshape(3,2)

In [12]:
B

array([[10., 12.],
       [14., 16.],
       [18., 20.]])

In [13]:
C = A * B 

In [14]:
C

array([[  0.,  12.],
       [ 28.,  48.],
       [ 72., 100.]])

## Hadamard product of two matrices (complex)

Let $\mathbf{A}, \mathbf{B} \in \mathcal{C}^{N \times M}$ matrices with complex entries. The hadamard product results: 

$$ \mathbf{C} = \mathbf{C}_R + \mathcal{i}*\mathbf{C}_I $$

where

$$\mathbf{C}_R = \mathbf{A}_R \circ \mathbf{B}_R - \mathbf{A}_I \circ \mathbf{B}_I  $$

e

$$ \mathbf{C}_R = \mathbf{A}_R \circ \mathbf{B}_I + \mathbf{A}_I \circ \mathbf{B}_R . $$

**Pseudocode:**

    C_R = hadamard(Real(A), Real(B)) - hadamard(Imag(A), Imag(B))
    C_I = hadamard(Real(A), Imag(B)) + hadamard(Imag(A), Real(B))

    C = C_R + imag*C_I

## Exercises

* Create the functions below according to `template.py`:
  * `hadamard_real`
  * `hadamard_complex`
* These functions must pass the following tests defined in `test_template.py`:
  * `test_hadamard_real_different_shapes`
  * `test_hadamard_real_compare_asterisk`
  * `test_hadamard_real_ignore_complex`
  * `test_hadamard_complex_compare_asterisk`