# Matrix-vector product

This notebook shows some algorithms to perform a matrix-vector product with real and complex entries. 

## Matrix-vector product (real)

Let $\mathbf{A \in \mathbb{R}^{N \times M}}$ be a matrix and $\mathbf{x} \in \mathbb{R}^M$ a vector given by: 

$$
\mathbf{A} = \begin{bmatrix}
a_{00}    & \cdots & a_{0(M-1)}\\
\vdots    &        &  \vdots   \\
a_{(N-1)0}& \cdots &  a_{(N-1)(M-1)}
\end{bmatrix}
$$

and 

$$ \mathbf{x} = \begin{bmatrix}
x_{0} \\
x_{1} \\
\vdots \\
x_{M-1}
\end{bmatrix}.
$$

A matrix-vector product is defined as 

$$
\mathbf{y} = \mathbf{A}\mathbf{x} = \begin{bmatrix}
a_{00}x_{0} + \cdots + a_{0(M-1)} x_{M-1} \\
\vdots & &\\
a_{(N-1)0} x_{0} + \cdots + a_{(N-1)(M-1)} x_{M-1}
\end{bmatrix}.
$$
Notice that the result of a matrix-vector product is a vector $\mathbf{y}$ with dimension of $N \times 1$. 

**Pseudocode.1 (doubly nested) :**
    
    for i = 0:N-1
        for j = 0:M-1
            y[i] += A[i,j]x[j]

**Pseudocode.2 (dot product formulation):**
    
    for i = 0:N-1
            y[i] = dot(A[i,:], x[:])

**Pseudocode.3 (scalar-vector formulation):**
    
    for j = 0:M-1
            y[:] += x[j]*A[:,j]

In [1]:
import numpy as np

In [2]:
x = np.arange(4,dtype=float)

In [3]:
x

array([0., 1., 2., 3.])

In [4]:
A = np.arange(20,dtype=float).reshape(5,4)

In [5]:
A

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]])

In [6]:
y_dot = np.dot(A,x)

In [7]:
y_dot

array([ 14.,  38.,  62.,  86., 110.])

In [8]:
y_matmul = A@x

In [9]:
y_matmul

array([ 14.,  38.,  62.,  86., 110.])

## Matrix-vector product (complex)

Let $\mathbf{A \in \mathbb{C}^{N \times M}}$ be a matrix with complex entries given by:

$$ \mathbf{A} = \mathbf{A}_R + i*\mathbf{A}_I$$
and a vector $\mathbf{x} \in \mathbb{C}^M $ also with complex entries equal to

$$\mathbf{x} = \mathbf{x}_R + i*\mathbf{x}_I $$.

The matrix-vector product results in a vector $\mathbf{y}$ with dimension of $N \times 1$ defined as

$$ \mathbf{y} = \mathbf{y}_R + i*\mathbf{y}_I $$
where

$$\mathbf{y}_R = \mathbf{A}_R \mathbf{x}_R - \mathbf{A}_I \mathbf{x}_I $$
and

$$ \mathbf{y}_I = \mathbf{A}_R \mathbf{x}_I + \mathbf{A}_I \mathbf{x}_R .$$

**Pseudocode:**

    y_R = matvec(Real(A), Real(x)) - matvec(Imag(A), Imag(x))
    y_I = matvec(Real(A), Imag(x)) + matvec(Imag(A), Real(x))

    y = y_R + imag*y_I

## Exercises

* Create the functions below according to `template.py`:
  * `matvec_real_simple`
  * `matvec_real_dot`
  * `matvec_real_columns`
  * `matvec_complex`
* These functions must pass the following tests defined in `test_template.py`:
  * `test_matvec_real_input_doesnt_match`
  * `test_matvec_real_functions_compare_numpy_dot`
  * `test_matvec_real_functions_ignore_complex`
  * `test_matvec_complex_compare_numpy_dot`
  * `test_matvec_complex_invalid_function`