# Triangular matrices

Consider two $N \times N$ matrices $\mathbf{U}$ and $\mathbf{L}$ given by:

$$\mathbf{U} 
= \left[ \begin{array}{ccccc}
u_{00} & u_{01} & u_{02} & \cdots & u_{0(N-1)} \\
       & u_{11} & u_{12} & \cdots & u_{1(N-1)} \\
       &        & u_{22} & \cdots & u_{2(N-1)}  \\
       &        &        & \ddots & \vdots  \\
       &        &        &        & u_{(N-1)(N-1)}
\end{array} \right]
$$

and

$$
\mathbf{L} 
= \left[ \begin{array}{ccccc}
l_{00} & & & & \\
\vdots & \ddots & & & \\
l_{(N-3)0} & \cdots & l_{(N-3)(N-3)} & &\\
l_{(N-2)0} & \cdots & l_{(N-2)(N-3)} & l_{(N-2)(N-2)} &\\
l_{(N-1)0} & \cdots & l_{(N-1)(N-3)} & l_{(N-1)(N-2)} & l_{(N-1)(N-1)}
\end{array} \right] \: .
$$

The matrix $\mathbf{U}$ is called **upper triangular** and has all the elements below the main diagonal equal to zero. Similarly, the matrix $\mathbf{L}$ is called **lower triangular** and has all the elements above the main diagonal equal to zero.

Let $\mathbf{x}$ be a $N \times 1$ vector given by:

$$\mathbf{x} = 
\left[ \begin{array}{c}
x_{0} \\
\vdots \\
x_{(N-1)}
\end{array} \right] \: .
$$

By using the notebook `matrix-vector.ipynb`, it can be shown that the product $\mathbf{y} = \mathbf{U} \mathbf{x}$ can be calculated by following different algorithms:

**Algorithm 1**
    
    for i = 0:N-1
        for j = 0:N-1
            y[i] = y[i] + U[i,j]*x[j]

**Algorithm 2**
    
    for i = 0:N-1
        for j = i:N-1
            y[i] = y[i] + U[i,j]*x[j]

**Algorithm 3**

    for i = 0:N-1
        y[i] = dot(U[i,i:],x[i:])

**Algorithm 4**

    for j = 0:N-1
        for i = 0:j
            y[i] = y[i] + U[i,j]*x[j]

**Algorithm 5**

    for j = 0:N-1
        y[:j] = y[:j] + scalar_vec(x[j], U[:j,j])

Similarly, there are different algorithms to compute the product $\mathbf{z} = \mathbf{L} \mathbf{x}$:

**Algorithm 6**
    
    for i = 0:N-1
        for j = 0:N-1
            z[i] = z[i] + L[i,j]*x[j]

**Algorithm 7**
    
    for i = 0:N-1
        for j = 0:i
            z[i] = z[i] + L[i,j]*x[j]

**Algorithm 8**

    for i = 0:N-1
        z[i] = dot(L[i,:i],x[:i])

**Algorithm 9**

    for j = 0:N-1
        for i = j:N-1
            z[i] = z[i] + L[i,j]*x[j]

**Algorithm 10**

    for j = 0:N-1
        z[j:] = z[j:] + scalar_vec(x[j], L[j:,j])

Note that some of the algorithms presented above access the null elements of the triangular matrices and other algorithms do not access the null elements.

### Exercise

* Create the functions below according to `template.py`:
  * `matvec_triu_prod3`
  * `matvec_triu_prod5`
  * `matvec_tril_prod8`
  * `matvec_tril_prod10`

* The functions **must**: 
  * verify if the given triangular matrix is square;
  * verify if `x` is a numpy array with ndim = 1; 
  * assert that the number of rows/columns of the triangular matrix is equal to the number of elements forming `x`;
  * ignore possible imaginary of the input parameters;

Additionally, **create at least two tests**. The first test must compare the results produced by the functions `matvec_triu_prod3` and `matvec_triu_prod5` with the result produced by the routine [`numpy.dot`](https://numpy.org/doc/stable/reference/generated/numpy.dot.html). The second test must compare the results produced by the functions `matvec_tril_prod8` and `matvec_tril_prod10` with the result produced by the routine [`numpy.dot`](https://numpy.org/doc/stable/reference/generated/numpy.dot.html).

#### How to create triangular matrices from full matrices?

The code below uses the routines [`Random generator`](https://numpy.org/doc/stable/reference/random/generator.html), [`numpy.triu`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.triu.html), and [`numpy.tril`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.tril.html).

In [1]:
import numpy as np
import my_functions as mf

In [2]:
N = 5

In [3]:
rng = np.random.default_rng(5)
A = 10*rng.random((N,N))

In [4]:
U = np.triu(A)

In [5]:
L = np.tril(A)

In [6]:
A

array([[8.05002924, 8.0794079 , 5.15325561, 2.8580138 , 0.53930702],
       [3.83368881, 4.08473205, 0.45275194, 0.48757711, 9.99176115],
       [6.52369112, 2.34510202, 4.34947552, 9.74186193, 8.97677608],
       [8.44231038, 3.92404664, 4.93023019, 6.76689352, 0.60802713],
       [5.55596117, 2.71451605, 8.79651173, 0.64214437, 6.79181533]])

In [7]:
U

array([[8.05002924, 8.0794079 , 5.15325561, 2.8580138 , 0.53930702],
       [0.        , 4.08473205, 0.45275194, 0.48757711, 9.99176115],
       [0.        , 0.        , 4.34947552, 9.74186193, 8.97677608],
       [0.        , 0.        , 0.        , 6.76689352, 0.60802713],
       [0.        , 0.        , 0.        , 0.        , 6.79181533]])

In [8]:
L

array([[8.05002924, 0.        , 0.        , 0.        , 0.        ],
       [3.83368881, 4.08473205, 0.        , 0.        , 0.        ],
       [6.52369112, 2.34510202, 4.34947552, 0.        , 0.        ],
       [8.44231038, 3.92404664, 4.93023019, 6.76689352, 0.        ],
       [5.55596117, 2.71451605, 8.79651173, 0.64214437, 6.79181533]])